name: 'cgu'
version: '1.0.0'
config-version: 2

profile: 'cgu'

on-run-start:
  - "{{ gcs_auth() }}"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"

models:
  cgu:
    +persist_docs:
      relation: true
      columns: true

    bronze:
      +schema: bronze
      +materialized: table

    silver:
      +schema: silver
      +materialized: table

    gold:
      +schema: gold
      +materialized: table