cgu:
  target: bronze
  outputs:

    bronze:
      type: duckdb
      path: 'duckdb/terceirizados-bronze.duckdb'
      threads: 4
      extensions:
        - httpfs
        - parquet

    silver:
      type: duckdb
      path: 'duckdb/terceirizados-silver.duckdb'
      threads: 4
      extensions:
        - httpfs
        - parquet

    gold:
      type: duckdb
      path: 'duckdb/terceirizados-gold.duckdb'
      threads: 4
      extensions:
        - httpfs
        - parquet